
baseURL = "https://jobplorer.com/"
languageCode = "en-us"
title = "Jobplorer"
theme = "ananke"
enableRobotsTXT = true
buildFuture = false

[pagination]
  pagerSize = 12

[params]
  mainSections = ["posts"]
